# Specify the skip mode triggered by a specified chapter, with optional values: none|auto|manual (default)
mode=manual
## Specify the language for the OSD message display of the script, default: eng
language=eng
## Specify the timeout time for the OSD message display of the script, unit: seconds. Default: 15
timeout=15
#Extra chapter names to be skipped
categories=opening>^OP/ OP$/^[Oo]pening/[Oo]pening$/オープニング; ending>^ED/ ED$/^[Ee]nding/[Ee]nding$/エンディング; credits>^[ Cc]redits/[Cc]redits$; prologue>^[Pp]rologue/^[Ii]ntro; preview>[Pp]review$/^[Pp]review/announcement; PartAB>Part [AB]/Ending 1; PartC>Part C
#Specify the chapters to be skipped
skip=opening;ending;credits;prologue;preview

# Specify the maximum noise level to trigger skipping silence, in dB units. 
# Default value: -40. -60 is very sensitive,
# while -10 is more tolerant of noise
silence_audio_level=-40
# Specify the duration of silence detection that triggers skipping. Default value: 0.7.
silence_duration=0.7
# The first detected silence_duration will be ignored for the number of seconds defined in this option, and it will continue to skip until the next silence_duration.
# 0 disables it, or specify a specific number of seconds. Default value: 1.
ignore_silence_duration=5
# Specify the minimum number of seconds to accept skipping before the configured silence_duration.
# 0 disables it, or specify a specific number of seconds. Default value: 0.
min_skip_duration=0
# Specify the maximum number of seconds to accept skipping before the configured silence_duration.
# 0 disables it, or specify a specific number of seconds. Default value: 120.
max_skip_duration=120
# Specify whether to mute the audio when skipping, as fast-forwarded audio can sound piercing. Default value: no.
force_mute_on_skip=yes
# Specify the path to the skip chapter history record file. Supports absolute and relative paths
history_path=~~/files/chapterskip_history.json
